import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import metaRouter from "./meta";
import usersRouter from "./users";
import jobsRouter from "./jobs";
import proposalsRouter from "./proposals";
import conversationsRouter from "./conversations";
import reviewsRouter from "./reviews";
import notificationsRouter from "./notifications";
import paymentsRouter from "./payments";
import adminRouter from "./admin";
import verificationsRouter from "./verifications";
import contractsRouter from "./contracts";
import walletRouter from "./wallet";
import invoicesRouter from "./invoices";
import disputesRouter from "./disputes";
import uploadsRouter from "./uploads";
import legalRouter from "./legal";
import settingsRouter from "./settings";
import analyticsRouter from "./analytics";
import recommendationsRouter from "./recommendations";
import savedSearchesRouter from "./savedSearches";
import reportsRouter from "./reports";
import seoRouter from "./seo";
import scoringRouter from "./scoring";
import devicesRouter from "./devices";
import paymentsGatewayRouter from "./paymentsGateway";
import escrowAdminRouter from "./escrowAdmin";
import payoutBatchesRouter from "./payoutBatches";
import featuredRouter from "./featured";
import subscriptionsRouter from "./subscriptions";
import currenciesRouter from "./currencies";
import reconciliationRouter from "./reconciliation";
import moderationRouter from "./moderation";
import metricsRouter from "./metrics";
import invoicesTaxRouter from "./invoicesTax";
import { attachUser } from "../lib/auth";

const router: IRouter = Router();

router.use(attachUser);

router.use(healthRouter);
router.use(authRouter);
router.use(metaRouter);
router.use(usersRouter);
router.use(jobsRouter);
router.use(proposalsRouter);
router.use(conversationsRouter);
router.use(reviewsRouter);
router.use(notificationsRouter);
router.use(paymentsRouter);
router.use(verificationsRouter);
router.use(contractsRouter);
router.use(walletRouter);
router.use(invoicesRouter);
router.use(disputesRouter);
router.use(uploadsRouter);
router.use(legalRouter);
router.use(settingsRouter);
router.use(analyticsRouter);
// Phase 3
router.use(recommendationsRouter);
router.use(savedSearchesRouter);
router.use(reportsRouter);
router.use(seoRouter);
router.use(scoringRouter);
router.use(adminRouter);

// Phase 4
router.use(devicesRouter);
router.use(paymentsGatewayRouter);
router.use(escrowAdminRouter);
router.use(payoutBatchesRouter);
router.use(featuredRouter);
router.use(subscriptionsRouter);
router.use(currenciesRouter);
router.use(reconciliationRouter);
router.use(moderationRouter);
router.use(metricsRouter);
router.use(invoicesTaxRouter);

export default router;
